[database]
host        = localhost
db_name     = shric8ey_cms
;db_name     = shric8ey_demo_cms
db_user     = shric8ey_root
db_password = Rollout@123#

[application]
app_email = mailer@myapp.com
app_url   = myapp.com


