[database]
host        = localhost
;db_name     = shric8ey_cms
db_name     = shric8ey_demo_cms
db_user     = shric8ey_root
db_password = Rollout@123#

[application]
logo = logo-scbc.png
app_email = donotreply@shrichandragroup.com
app_url   = https://demo.shrichandragroup.com/
app_contact = +91-884-2361567,69
app_rights = 2024 PVS Consultancy Services. All Right Reserved.

[headoffice]
app_hadd1 = 7-70-62/A, 1st Floor,
app_hadd2 = Ramya Royale, Ramanayya Peat,
app_hadd3 = Kakinada-533 003, A.P. INDIA,
app_hadd4 = GST: 37AAECR9430L1ZX.

[corpoffice]
app_cadd1 = Flat No: 904, 910,
app_cadd2 = Sagar Tech Plaza, B-Andheri Kurla Sakinaka,
app_cadd3 = Andheri East, Mumbai-400072, Maharastra India.
app_cadd4 = GST: 27AAECR9430L1ZY.

[urls]
url_home    =	https://shrichandragroup.com
url_about	=	https://shrichandragroup.com/about
url_buss	=	https://shrichandragroup.com
url_contact	=	https://shrichandragroup.com/contact
