[database]
host        = localhost
db_name     = shric8ey_cms
;db_name     = shric8ey_demo_cms
db_user     = shric8ey_root
db_password = Rollout@123#

[application]
app_email = donotreply@shrichandragroup.com
app_url   = https://cms.pvs-consultancy.com/
app_contact = 0884-2361567,69

[headoffice]
app_hadd1 = 7-70-62/A, 1st Floor,
app_hadd2 = Ramya Royale, Ramanayya Peat,
app_hadd3 = Kakinada-533 003, A.P. INDIA,
app_hadd4 = GST: 37AAECR9430L1ZX.

[corpoffice]
app_cadd1 = Flat No: 904, 910,
app_cadd2 = Sagar Tech Plaza, B-Andheri Kurla Sakinaka,
app_cadd3 = Andheri East, Mumbai-400072, Maharastra India.
app_cadd4 = GST: 27AAECR9430L1ZY.

[mail]
email_host = smtp.office365.com
email_port = 587
email_name = ShriChandraGroup
smtp_auth  = true
email_user = donotreply@shrichandragroup.com
app_pwd    = xxzmgnvhyfqxwpgw

[urls]
url_home    =	https://pvs-consultancy.com/
url_about	=	https://pvs-consultancy.com/about
url_buss	=	https://pvs-consultancy.com/services/
url_contact	=	https://pvs-consultancy.com/contact/
